sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-9
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-opensuse-leap
#  - INSTANCE=default-fedora-latest Docker only failure on passwd
  - INSTANCE=instance-ubuntu-1404
  - INSTANCE=instance-ubuntu-1604
  - INSTANCE=instance-debian-7
  - INSTANCE=instance-debian-8
  - INSTNACE=instance-debian-9
  - INSTANCE=instance-centos-6
  - INSTANCE=instance-centos-7
  - INSTANCE=instance-opensuse-leap
#  - INSTANCE=instance-fedora-latest

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
